/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCalendar: typeof import('./src/components/ActivityCalendar.vue')['default']
    BaseCard: typeof import('./src/components/ui/BaseCard.vue')['default']
    BeamsBackground: typeof import('./src/components/BeamsBackground.vue')['default']
    CommentEditor: typeof import('./src/components/comments/CommentEditor.vue')['default']
    CommentItem: typeof import('./src/components/comments/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/comments/CommentList.vue')['default']
    CommentSection: typeof import('./src/components/comments/CommentSection.vue')['default']
    CommentSortSelect: typeof import('./src/components/comments/CommentSortSelect.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCalendar: typeof import('element-plus/es')['ElCalendar']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HomeLayout: typeof import('./src/components/layout/HomeLayout.vue')['default']
    HomeSection: typeof import('./src/components/layout/HomeSection.vue')['default']
    IconRenderer: typeof import('./src/components/ui/IconRenderer.vue')['default']
    ImageModal: typeof import('./src/components/ImageModal.vue')['default']
    ImagePreview: typeof import('./src/components/ui/ImagePreview.vue')['default']
    MarqueeCarousel: typeof import('./src/components/MarqueeCarousel.vue')['default']
    MediaCard: typeof import('./src/components/ui/MediaCard.vue')['default']
    MetricCard: typeof import('./src/components/ui/MetricCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    PostContent: typeof import('./src/components/PostContent.vue')['default']
    QuickNavDock: typeof import('./src/components/QuickNavDock.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RoadMapCard: typeof import('./src/components/ui/RoadMapCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/layout/SectionHeader.vue')['default']
    ShinyText: typeof import('./src/components/ShinyText.vue')['default']
    TagBadge: typeof import('./src/components/ui/TagBadge.vue')['default']
    TopicList: typeof import('./src/components/ui/TopicList.vue')['default']
  }
}
