<script setup lang="ts">
import { computed } from 'vue'
import {
  Activity,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  Award,
  BookOpen,
  Bot,
  Brain,
  Briefcase,
  Bug,
  Building2,
  Calendar,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock,
  Code2,
  Command,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  FileCode,
  FilePlus2,
  FileText,
  Flame,
  FlaskConical,
  GitBranch,
  GitCommit,
  Github,
  GitMerge,
  Globe,
  ImagePlus,
  Info,
  Layers,
  Link2,
  Mail,
  MapPin,
  Medal,
  Menu,
  MessageCircle,
  MessageSquare,
  MessagesSquare,
  Newspaper,
  Package,
  Plus,
  Puzzle,
  RadioTower,
  Reply,
  Search,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Star,
  Tags,
  Terminal,
  ThumbsUp,
  Type,
  User,
  Users,
  Wrench,
  X,
  Zap,
} from 'lucide-vue-next'
import type { IconName } from '../../types/home'

const props = withDefaults(defineProps<{
  name: IconName | string
  className?: string
}>(), {
  className: 'w-4 h-4',
})

const iconMap = {
  activity: Activity,
  'arrow-down-up': ArrowDownUp,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  award: Award,
  'book-open': BookOpen,
  bot: Bot,
  brain: Brain,
  briefcase: Briefcase,
  'bug': Bug,
  'building-2': Building2,
  calendar: Calendar,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  clock: Clock,
  'code-2': Code2,
  command: Command,
  cpu: Cpu,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  eye: Eye,
  'file-code': FileCode,
  'file-plus-2': FilePlus2,
  'file-text': FileText,
  flame: Flame,
  'flask-conical': FlaskConical,
  'git-branch': GitBranch,
  'git-commit': GitCommit,
  github: Github,
  'git-merge': GitMerge,
  globe: Globe,
  'image-plus': ImagePlus,
  info: Info,
  layers: Layers,
  link: Link2,
  mail: Mail,
  'map-pin': MapPin,
  medal: Medal,
  menu: Menu,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  'messages-square': MessagesSquare,
  newspaper: Newspaper,
  package: Package,
  plus: Plus,
  puzzle: Puzzle,
  'radio-tower': RadioTower,
  reply: Reply,
  search: Search,
  server: Server,
  settings: Settings,
  shield: Shield,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  tags: Tags,
  terminal: Terminal,
  'thumbs-up': ThumbsUp,
  type: Type,
  user: User,
  users: Users,
  wrench: Wrench,
  x: X,
  zap: Zap,
}

const iconComponent = computed(() => iconMap[props.name as keyof typeof iconMap] ?? Zap)
</script>

<template>
  <component :is="iconComponent" :class="className" />
</template>
